### ISSUE TITLE
The command '/bin/sh -c go get github.com/pdevine/go-asciisprite' returned a non-zero code: 2

### ISSUE THREAD

**Issue by teunbruijnen** [pdevine/go-asciisprite#4]
When trying to docker build I'm receiving this error:

```
Step 3/9 : RUN go get github.com/pdevine/go-asciisprite
 ---> Running in 725aaf48562c
# github.com/pdevine/go-asciisprite
src/github.com/pdevine/go-asciisprite/block.go:155:8: undefined: abs
src/github.com/pdevine/go-asciisprite/block.go:156:9: undefined: abs
The command '/bin/sh -c go get github.com/pdevine/go-asciisprite' returned a non-zero code: 2
```

**Comment by pdevine** [comment]
Woops! Really sorry about this. This should be fixed now, but I was under the mistaken impression that no one is using the library! I've been changing around a lot of the routines though so you may run into some issues as the library evolves.

What are you trying to build? I'm thinking maybe I need to start doing proper releases.

**Comment by teunbruijnen** [comment]
It came up on the docker "onboarding page", inside the tutorial that started just after downloading Docker Desktop here: [https://hub.docker.com/?overlay=onboarding](https://hub.docker.com/?overlay=onboarding)

The error occured while trying to build "cheers2019", from the repository [https://github.com/docker/doodle.git](https://github.com/docker/doodle.git). 

Thanks for the quick reply and the fix, I tested and it works now!

**Comment by pdevine** [comment]
Cool. I didn't realize they were still using it. I wrote the doodles when when I still worked at Docker, but thought they had gotten rid of them.
